SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `java2` DEFAULT CHARACTER SET utf8 ;
USE `java2` ;

-- -----------------------------------------------------
-- Table `Java2`: `users`, `bets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;
DROP TABLE IF EXISTS `bets` ;

CREATE TABLE IF NOT EXISTS `users` (
  `UserID` INT(11) NOT NULL AUTO_INCREMENT,
  `FirstName` CHAR(32) NOT NULL,
  `LastName` CHAR(32) NOT NULL,
  PRIMARY KEY (`UserID`)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1002;

CREATE TABLE IF NOT EXISTS bets (
  BetID INT(11) AUTO_INCREMENT,
  UserID INT(11) NOT NULL,
  EventID INT(11) NOT NULL,
  Bet_Sum BIGINT UNSIGNED NOT NULL,
  Winning_Choice BOOLEAN NOT NULL,
  PRIMARY KEY(BetID),
  FOREIGN KEY(UserID) REFERENCES users(UserID),
  FOREIGN KEY(EventID) REFERENCES events(EventID)
)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;