SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `TotalizatorDB_test` DEFAULT CHARACTER SET utf8 ;
USE `TotalizatorDB_test`;


DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `main_events`;
DROP TABLE IF EXISTS `events` ;
DROP TABLE IF EXISTS `bets` ;
DROP TABLE IF EXISTS `accounts` ;
DROP TABLE IF EXISTS `userAccounts` ;
DROP TABLE IF EXISTS `transactions` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;